### ISSUE TITLE
Make release

### ISSUE THREAD

**Issue by aTei** [UltCombo/poly-checked#1]
Hi. Can you do github release of this poly? It should not take more than 2 mins.
Here is how to https://help.github.com/articles/creating-releases/
Thanks :)

**Comment by UltCombo** [comment]
Oh, I had almost forgot about this repo. I'd rather use npm/bower for distribution, but a GitHub release won't hurt anyway. Done: https://github.com/UltCombo/poly-checked/releases

**Comment by aTei** [comment]
:+1:
